CREATE TABLE Majors
(MajorID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) UNIQUE NOT NULL)

CREATE TABLE Students(
StudentID INT PRIMARY KEY IDENTITY(1,1),
StudentNumber CHAR(10) UNIQUE NOT NULL,
StudentName VARCHAR(100) NOT NULL,
MajorID INT REFERENCES Majors(MajorID) NOT NULL)

CREATE TABLE Subjects(
SubjectID INT PRIMARY KEY IDENTITY(1,1),
SubjectName VARCHAR(50) NOT NULL)

CREATE TABLE Agenda(
StudentID INT REFERENCES Students(StudentID),
SubjectID INT REFERENCES Subjects(SubjectID),
PRIMARY KEY (StudentID,SubjectID))

CREATE TABLE Payments(
PaymentID INT PRIMARY KEY IDENTITY(1,1),
PaymentDate DATETIME2 NOT NULL,
PaymentAmmount DECIMAL(11,2) NOT NULL,
StudentID INT REFERENCES Students(StudentID))

