CREATE TABLE Cities(
CityID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL)

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
[Birthday] DATE,
CityID INT REFERENCES Cities(CityID) )


CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY(1,1),
CustomerID INT REFERENCES Customers(CustomerID) NOT NULL )

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL)

CREATE TABLE Items(
ItemID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT REFERENCES ItemTypes(ItemTypeID))

CREATE TABLE OrderItems(
OrderID INT REFERENCES Orders(OrderID),
ItemID INT REFERENCES Items(ItemID),
PRIMARY KEY (OrderId,ItemID))
